--- 
title: "Case studies of declining birds in Tennessee"
author: "Max Patterson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      sharing:
        facebook: false
        twitter: false
documentclass: book
bibliography: [bibliography.bib]
biblio-style: apalike
link-citations: yes
github-repo: https://github.com/pattemj0/Datastory3.git
description: "A literature review of SDG 15: Life on Land with a special focus on birds in North America and the deforestation that impacts them."
---

# Overview of SDG 15, Life on land {-}

One of the biggest concerns our society faces today is the loss of biodiversity. Land-use changes associated with resource extraction and development have caused a lot of habitat loss. Research shows that there have been major declines in populations in many species of North American birds (avifauna decline paper). Species that migrate to the neotropics (especially South America) show signs of decline in particular (neotropical migrants paper). In this story, I will be taking a closer look at the relationship between the decline in avifauna and deforestation. Deforestation is a large problem in America, especially South America. In this story I will look at several case studies of bird declines in relation to forest loss.

# Loss of Bird Diversity

In recent years there has been a drastic increase in citizen science. This has vastly improved our ability to collect data in large quantities and on large scales. Our knowledge of bird populations specifically has drastically improved with databases such as the [BBS](https://www.usgs.gov/centers/eesc/science/north-american-breeding-bird-survey), [Christmas Bird Count](https://www.audubon.org/community-science/christmas-bird-count), and the rise of [eBird](https://ebird.org/home) in more recent years. Thanks to this new form of data, scientists have been able to use these data to analyze the status of birds on a continental scale. Unfortunately, what this has shown is that bird populations in North America are undergoing a large-scale decline (Rosenberg et al., 2019). This is highly concerning because such a loss in biodiversity could have cascading effects on the entire biosphere. This research shows that birds in eastern forests are undergoing a decline close to 20%. Other research (Robbins et al. 1989) conducted using similar methods shows that birds who migrate south to tropical regions are undergoing more than permanent residents showing that population declines as a result of habitat loss may be worse in areas where citizen science is less available and as a result these declines may go undetected. As residents of the Cumberland Plateau in Tennessee, this is highly concerning because it shows that bird species in our own ecosystems are in decline. Many of the birds we have in Tennessee migrate to tropical areas. As a result it is important to understand how changes in our own landscapes as well as landscapes far away can affect us so that we can better understand the threats to our ecosystems and what impacts we can have.


# Deforestation and Forest Change

## Tennessee

Research shows that in Tennessee native forests are undergoing a serious decline due to land use change (Evans, 2005) . What's worse, forests that have not been intentionally disturbed are undergoing changes due to altered disturbance regimes both anthropogenically and because of climatic shifts (Flatley et al. 2013). Specifically, it shows that fire frequencies have changed over time resulting in shifts in species composition of forests. This could have a significant impact on bird populations as well as other taxa as it can result in ecological shifts, habitat loss, edge effects, and habitat fragmentation. The research highlights how important it is to conserve forest habitat in the Southeast in order to maintain habitat for species associated with these ecosystems.

## Tropics

Recent research shows that forests in South America have been undergoing a significant decline due to anthropogenic pressures (Etter et al., 2005). As residents of Tennessee we may consider this problem to be far away with little impact on our lives, however, this is not the case at all. Many bird species that inhabit Tennessee migrate to these forests. As a result, disturbances to these forests can directly impact the population sizes of these species causing disruptions to ecological dynamics in Tennessee and threatening species that are important to us. Therefore the ecological integrity of forests in South America should be of utmost importance to us.

### Colombia

In Colombia, anthropogenic pressures such as population growth and the expansin of agriculture have caused forest loff on a large scale. Research shows that 35% of Colombia's landscapes had been cleared by 1998. Most of this landscape had been cleared for agriculture such as cattle pasture. Predictions show that land will continue to be cleared in Colombia which can have devestating costs. Land-use planning is not well developed in this country though so improved data and monitoring programs could be highly beneficial in midigating these costs in this context (Etter et al., 2005). 

### Venezuela

The situation surroundign deforestation in Venezuela is highly complex. There are two primary drivers of deforestation here. The first is from settlers clearing land for agriculture in order to claim property rights in the future, and the second involves timber extraction companies legally clearing forests with government permits. As a result, politics in Venezuela, have a large impact on the future of their ecosystems (Moreno et al., 2005).

# Case studies of species in decline

In this story we will look at several examples of bird species that are in decline. Each of these species faces different challenges because of their unique ecological niche and habitat preferences.

## Red-headed Woodpecker

The first case study is the Red-headed woodpecker. Data from the BBS and CBC show a decline in Red-headed woodpecker populations since the 1960s. To understand this decline, a study from 2017 compared several ecological factors to better understand it including increases in predation from accipiters such as hawks, competition from other species such as Red-bellied woodpeckers and invasive European Starlings, and finally changes in forest cover.  The study found that increased forest cover was significantly correlated to Red-headed Woodpecker declines (Koenig et al.,). It is possible that this is partly due to changes in fire frequencies resulting in forest change.

## Cerulean Warbler

The Cerulean Warbler is a bird that relies on forests with complex structure and ecological dynamics. As a result they may be more sensitive to anthropogenic disturbances such as deforestation. A recent study showed that in areas where forests had been cleared, edge effects had a significan impact on Cerulean Warblers. There numbers increase as with distance from the edge of the forest for 340 meters (Wood et al., 2006). As a result, clearing forests has negative impacts on this species. On a more positive note, another study found that forestry can be done in a manner that increases the abundance of Cerulean Warblers as well as other bird species (Sheehan et al., 2014). This is good news because it shows that it is possible to extract nutrients from a landscape that allows us to coexist with native species.

## Golden-winged Warbler

Another species that has undergone significant declines in Tennessee is the Golden-winged Warbler. In contrast to the Cerulean Warbler, the Golden-winged Warbler relies on shruby edge habitat. Forest succession and habitat loss is a large contributing factor to it's decline alongside ecological interactions with other species resulting from widespread ecological change occuring in recent decades. Habitat loss in South and central America where these birds migrate in the summer is also a large factor in their declines (Buehler et al., 2007). The USDA Forest Service recommends creating suitable habitat in the Appalachian region where this species has undergone a severe decline, as well as the protection of their habitat in South America through ecologically sound agroforestry practices especially in coffee production. They also recommend conserving stop-over  locations on their migratory path along the Gulf of Mexico (Rohrbaugh et al., 2016).

## Whip-poor-will

The Whip-poor-will is another bird species in decline. A recent study has shown that core forest habitat with little disturbance is a strong predictor of Whip-poor-will abundance (Metz & Pease, 2025). As a result it would be interesting to compare forest decline in Tennessee with the abundance of this species to see if there is a visible trend.

# Bibliography {-}

Buehler, D. A., Roth, A. M., Vallender, R., Will, T. C., Confer, J. L., Canterbury, R. A., ... & Wood, P. B. (2007). Status and conservation priorities of Golden-winged Warbler (Vermivora chrysoptera) in North America. The Auk, 124(4), 1439-1456.

Etter, A., McAlpine, C., Wilson, K., Phinn, S., & Possingham, H. (2006). Regional patterns of agricultural land use and deforestation in Colombia. Agriculture, Ecosystems & Environment, 114(2-4), 369-386. https://doi.org/10.1016/j.agee.2005.11.013 

Evans, J. (2005). Assessing Forest Loss on the Cumberland Plateau: Implications for Forest Policy in Tennessee. Proceedings of the 11th Symposium on the Natural History of Lower Tennessee and Cumberland River Valleys, 3-13. https://www.apsu.edu/field-biology/files/11th_Symposium_Proceedings_2005.pdf#page=12

Flatley, W. T., Lafon, C. W., Grissino-Mayer, H. D., & LaForest, L. B. (2013). Fire history, related to climate and land use in three southern Appalachian landscapes in the eastern United States. Ecological Applications, 23(6), 1250-1266. https://doi.org/10.1890/12-1662.1 
Academia.edu

Koenig, W. D., Walters, E. L., & Rodewald, P. G. (2017). Testing alternative hypotheses for the cause of population declines: The case of the Red-headed Woodpecker. Condor, 119(1), 143-154. doi:10.1650/condor-16-101.1

Metz, E. M., & Pease, B. S. (2025, March 11). Avian conservation and ecology: Environmental relationships, decadal changes, and regional decline of eastern whip-poor-will (<em>antrostomus vociferus</em>) and Chuck-Will’s-widow (<em>antrostomus carolinensis</em>). Avian Conservation and Ecology -. https://ace-eco.org/vol19/iss1/art24/ 

Moreno, N., Quintero, R., Ablan, M., Barros, R., Dávila, J. A., Ramírez, H., Tonella, G., & Acevedo, M. F. (2007). Biocomplexity of deforestation in the Caparo tropical forest reserve in Venezuela: An integrated multi-agent and cellular automata model. Environmental Modelling & Software, 22(5), 664–673. https://doi.org/10.1016/j.envsoft.2005.12.022

Robbins, C. S., Sauer, J. R., Greenberg, R. S., & Droege, S. (1989). Population declines in North American birds that migrate to the neotropics. Proceedings of the National Academy of Sciences, 86(19), 7658-7662. doi.org 

Rohrbaugh, R. W., Buehler, D. A., Swarthout, S. B., King, D. I., Larkin, J. L., Rosenberg, K. V., Roth, A. M., Vallender, R., & Will, T. (2016). Conservation perspectives: Review of new science and primary threats to golden-winged warblers. In H. M. Streby, D. E. Andersen, & D. A. Buehler (Eds.), Golden-winged Warbler ecology, conservation, and habitat management (Studies in Avian Biology No. 49, pp. 207–221). CRC Press.

Rosenberg, K. V., Dokter, A. M., Blancher, P. J., Sauer, J. R., Smith, A. C., Smith, P. A., Stanton, J. C., Panjabi, A., Helft, L., Parr, M., & Marra, P. P. (2019). Decline of the North American avifauna. Science, 366(6461), 120–124. https://doi.org/10.1126/science.aaw1313

Sheehan, J., Wood, P. B., Buehler, D. A., Keyser, P. D., Larkin, J. L., Rodewald, A. D., Wigley, T. B., Boves, T. J., George, G. A., Bakermans, M. H., Beachy, T. A., Evans, A., McDermott, M. E., Newell, F. L., Perkins, K. A., & White, M. (2014). Avian response to timber harvesting applied experimentally to manage Cerulean Warbler breeding populations. Forest Ecology and Management, 321, 5-18. https://doi.org/10.1016/j.foreco.2013.07.037

Wood, P. B., Bosworth, S. B., & Dettmers, R. (2006). Cerulean Warbler abundance and occurrence relative to large-scale edge and habitat characteristics. The Condor, 108(1), 154-165. doi.org

