# Loss of Bird Diversity

In recent years there has been a drastic increase in citizen science. This has vastly improved our ability to collect data in large quantities and on large scales. Our knowledge of bird populations specifically has drastically improved with databases such as the [BBS](https://www.usgs.gov/centers/eesc/science/north-american-breeding-bird-survey), [Christmas Bird Count](https://www.audubon.org/community-science/christmas-bird-count), and the rise of [eBird](https://ebird.org/home) in more recent years. Thanks to this new form of data, scientists have been able to use these data to analyze the status of birds on a continental scale. Unfortunately, what this has shown is that bird populations in North America are undergoing a large-scale decline (Rosenberg et al., 2019). This is highly concerning because such a loss in biodiversity could have cascading effects on the entire biosphere. This research shows that birds in eastern forests are undergoing a decline close to 20%. Other research (Robbins et al. 1989) conducted using similar methods shows that birds who migrate south to tropical regions are undergoing more than permanent residents showing that population declines as a result of habitat loss may be worse in areas where citizen science is less available and as a result these declines may go undetected. As residents of the Cumberland Plateau in Tennessee, this is highly concerning because it shows that bird species in our own ecosystems are in decline. Many of the birds we have in Tennessee migrate to tropical areas. As a result it is important to understand how changes in our own landscapes as well as landscapes far away can affect us so that we can better understand the threats to our ecosystems and what impacts we can have.
