# Deforestation and Forest Change

## Tennessee

Research shows that in Tennessee native forests are undergoing a serious decline due to land use change (Evans, 2005) . What's worse, forests that have not been intentionally disturbed are undergoing changes due to altered disturbance regimes both anthropogenically and because of climatic shifts (Flatley et al. 2013). Specifically, it shows that fire frequencies have changed over time resulting in shifts in species composition of forests. This could have a significant impact on bird populations as well as other taxa as it can result in ecological shifts, habitat loss, edge effects, and habitat fragmentation. The research highlights how important it is to conserve forest habitat in the Southeast in order to maintain habitat for species associated with these ecosystems.

## Tropics

Recent research shows that forests in South America have been undergoing a significant decline due to anthropogenic pressures (Etter et al., 2005). As residents of Tennessee we may consider this problem to be far away with little impact on our lives, however, this is not the case at all. Many bird species that inhabit Tennessee migrate to these forests. As a result, disturbances to these forests can directly impact the population sizes of these species causing disruptions to ecological dynamics in Tennessee and threatening species that are important to us. Therefore the ecological integrity of forests in South America should be of utmost importance to us.

### Colombia

In Colombia, anthropogenic pressures such as population growth and the expansin of agriculture have caused forest loff on a large scale. Research shows that 35% of Colombia's landscapes had been cleared by 1998. Most of this landscape had been cleared for agriculture such as cattle pasture. Predictions show that land will continue to be cleared in Colombia which can have devestating costs. Land-use planning is not well developed in this country though so improved data and monitoring programs could be highly beneficial in midigating these costs in this context (Etter et al., 2005). 

### Venezuela

The situation surroundign deforestation in Venezuela is highly complex. There are two primary drivers of deforestation here. The first is from settlers clearing land for agriculture in order to claim property rights in the future, and the second involves timber extraction companies legally clearing forests with government permits. As a result, politics in Venezuela, have a large impact on the future of their ecosystems (Moreno et al., 2005).
